version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SamDeploy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qqjcgf9cq9q7"
s3_prefix = "samdeploy"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
